### ISSUE TITLE
Change the X-axis settings?

### ISSUE THREAD

**Issue by Wigdens** [arneman/node-red-contrib-dashboard-bar-chart-data#11]
Hi and thanks for nice plugin! 
Is there any way to change the x-interval and x-size via input? I want some buttons on the dashboard to easily set different views (could be temporary, they don't have to permanently change the settings in the plug)?

As I understand the msg.settings is just on the output (and not to change the settings)?

/Fredrik

**Comment by arneman** [comment]
This is very complicated and needs a total refactoring AND the data-store may become very very large (with no need for most users):

At the moment the data will be internally stored in the way the x-interval and x-size properties are set. Example:
If x-interval is set to "hours", the data will be stored like this:
{2023040812: 2
,2023040813: 1
,2023040814: 4}
(YearMonthDayHour)

If x-interval is "days" the data will be stored like this:
{20230408: 7}

You cannot change this to "minutes" afterwards - the data is simply not there anymore. Caution: If you change the x-interval, the old data will be deleted - I haven't implemented a  function to convert the stored data, even it this is possible (e.g. from hours to days).

BTW: It is the same with "aggregator" node or others.
