### ISSUE TITLE
Error if topic doesn't contain a '/' character.

### ISSUE THREAD

**Issue by hydra** [arneman/node-red-contrib-dashboard-bar-chart-data#12]
If the topic doesn't contain a '/' character then the bar-char-data node generates an error:

```
"Error: Invalid property expression: unexpected ' ' at position 6"
```

Example topic: "Camera 1".

Example flow:

```json
[{"id":"e0a85d111084b254","type":"tab","label":"Flow 2","disabled":false,"info":"","env":[]},{"id":"0602ba4a44de5471","type":"bar-chart-data","z":"e0a85d111084b254","name":"bar-chart-data","x_interval":"seconds","x_size":"24","unit":"Liter","precision":"0","is_meter_reading":"False","agg_by":"sum","x":700,"y":220,"wires":[["7586214e837044da"]]},{"id":"7586214e837044da","type":"ui_chart","z":"e0a85d111084b254","name":"","group":"c716d8f1.4bb848","order":3,"width":"12","height":"4","label":"Liter letzte {{msg.settings.x_size}} Sekunden {{msg.data_sum}}","chartType":"bar","legend":"false","xformat":"HH:mm:ss","interpolate":"linear","nodata":"","dot":false,"ymin":"","ymax":"","removeOlder":"30","removeOlderPoints":"","removeOlderUnit":"60","cutout":0,"useOneColor":true,"colors":["#1f77b4","#aec7e8","#ff7f0e","#2ca02c","#98df8a","#d62728","#ff9896","#9467bd","#c5b0d5"],"outputs":1,"x":870,"y":220,"wires":[[]]},{"id":"65c4694bfbc89dd4","type":"inject","z":"e0a85d111084b254","name":"sensor","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"Camera 1","payload":"1","payloadType":"num","x":530,"y":220,"wires":[["0602ba4a44de5471"]]},{"id":"c716d8f1.4bb848","type":"ui_group","name":"bar-chart","tab":"957fd14a.a1277","order":1,"disp":true,"width":"12","collapse":false},{"id":"957fd14a.a1277","type":"ui_tab","name":"bar-chart","icon":"dashboard","disabled":false,"hidden":false}]
```

I want to have human friendly topic names, such as just "Camera 1", "Camera 2", etc, so that 
a) the legend can be displayed in the bar chart.
b) it still works.

Currently my workaround is to use a function node to prepend a fake `devices/` string to the `msg.topic` but then the legend also has the `devices/` prefix which isn't nice at all.

Screenshot of bad legends:

![image](https://user-images.githubusercontent.com/57075/214468442-46e9efac-2d27-40f5-8a6c-e6612dababf5.png)

Screenshot of example usage coming from 5 cameras:

![image](https://user-images.githubusercontent.com/57075/214468570-cca511b4-2521-45f8-bc98-5446cb8602c4.png)

**Comment by arneman** [comment]
The issue is the space in your topic "Camera 1", not the missing '/'. If you call it "Camera1" or "Camera_1" it'll work.

But anyway: this is not nice.

What also sucks: The whole bar-chart-data node will be unusable after you send a message with a topic with a space letter. You can fix this when you copy and paste the node an replace the old one.

Fixing this is not easy, so issue will be closed because there is an easy workaround.

**Comment by hydra** [comment]
@arneman Thanks for the workaround suggestions.  Suggest you also update the node documentation to reflect the requirement so that other users don't run into the same issue.
