### ISSUE TITLE
Negative payloads not supported

### ISSUE THREAD

**Issue by Jersh** [arneman/node-red-contrib-dashboard-bar-chart-data#6]
![image](https://user-images.githubusercontent.com/6068210/123244656-09f6e080-d4dc-11eb-8463-8dff257bc015.png)
Debug nodes take immediately before and after.

when I pipe in a negative value the node only sees undefined

My data is a track of a difference between target and actual. For example I have a target that increases by 1 every 5 minutes and a function that compares this to the actual and returns the difference.

So sometimes the difference is + and sometimes -. I assume I may be doing something wrong as when I specified the x limits of -140 to 60 is displays fine.

**Comment by Jersh** [comment]
So the issue is that when I set my aggregation to max on line 126 you declare
```
var oldVal = null;
```
which makes the next compare effectively against 0, which is always higher than a negative number.
likewise if I set it to Min and in the data period the value increases It wont be seen

**Comment by Jersh** [comment]
Is there way to just pass the last data received without any data aggregation? Maybe it needs an option for :None

**Comment by Jersh** [comment]
I have created a new option for no data aggregation. Selectable via the "None" option on the dropdown, will return the last value received in the time period.

Forked to here: https://github.com/Jersh/node-red-contrib-dashboard-bar-chart-data

**Comment by mcponta** [comment]
Hello, How can I install this version?

**Comment by Jersh** [comment]
> Hello, How can I install this version?

you can grab my version from [here:](https://github.com/Jersh/node-red-contrib-dashboard-bar-chart-data)

Download it to your node instance home folder and install using npm install /path

**Comment by mcponta** [comment]
Hello,tks for reply.
Unfortunately I am running  Nodered on IBM bluemix.
I will have to wait for a fix on original node.
Tks a lot Brother

**Comment by Jersh** [comment]
> Hello,tks for reply. Unfortunately I am running Nodered on IBM bluemix. I will have to wait for a fix on original node. Tks a lot Brother

Have you tried:
 `npm install https://github.com/Jersh/node-red-contrib-dashboard-bar-chart-data.git`

**Comment by mcponta** [comment]
> > Hello,tks for reply. Unfortunately I am running Nodered on IBM bluemix. I will have to wait for a fix on original node. Tks a lot Brother
> 
> Have you tried: `npm install https://github.com/Jersh/node-red-contrib-dashboard-bar-chart-data.git`

Yes I tried.
When running node red on IBM bluemix the access on root is denied.
The only way to install nodes is from manager pallet, on node red.
Commands npm on IBM terminal is Impossible.

**Comment by mcponta** [comment]
One more question.
Is possible run this node like a function?
O put the code in a function but not worked.
I am newbie on node red.

**Comment by Jersh** [comment]
> One more question. Is possible run this node like a function? O put the code in a function but not worked. I am newbie on node red.

no as its a collection of a few code blocks together.

Bare with me and I'll try to publish it temporarily.

**Comment by Jersh** [comment]
> > One more question. Is possible run this node like a function? O put the code in a function but not worked. I am newbie on node red.
> 
> no as its a collection of a few code blocks together.
> 
> Bare with me and I'll try to publish it temporarily.

Actually, why dont you do the following ( it'll help learn about the processes)
Fork my repo to your own git.
Edit the readme and package.json to give it a sightly different name
Then you can publish to npm yourself. (Tip! npm publish)

**Comment by mcponta** [comment]
> > > One more question. Is possible run this node like a function? O put the code in a function but not worked. I am newbie on node red.
> > 
> > 
> > no as its a collection of a few code blocks together.
> > Bare with me and I'll try to publish it temporarily.
> 
> Actually, why dont you do the following ( it'll help learn about the processes) Fork my repo to your own git. Edit the readme and package.json to give it a sightly different name Then you can publish to npm yourself. (Tip! npm publish)

Hello bro.
Unfortunately I don't have knowledge enough to do this myself alone. 
I have not brain enough to do that kkkk.
I make many things in node red, but I use only nodes when them have been done.

**Comment by Jersh** [comment]
> Hello bro. Unfortunately I don't have knowledge enough to do this myself alone. I have not brain enough to do that kkkk. I make many things in node red, but I use only nodes when them have been done.


Gotta Say Bro makes me want to help you less if your not even willing to try like.

**Comment by mcponta** [comment]
ok, you convinced me.  I will try to do this.
Thanks in advanced
Hugs from Brazil.
