### ISSUE TITLE
Not display minimum values

### ISSUE THREAD

**Issue by va7nic** [arneman/node-red-contrib-dashboard-bar-chart-data#7]
If I use bar-chart-data to display a daily minimum value of battery voltage on a solar system, no bar is displayed when I set the Aggregrate by to Minimum.  If I modify the node and select any other option than Minimum and let it run, it will then display the bar.  After a bar has been displayed, I can then go back and set it to Minimum and it will continue to display the proper minimum value until midnight, at which point I need to toggle the Aggregrate option to something and then back to minimum.  

Suggestions?

**Comment by mcponta** [comment]
Hello folks.
I have the same problem.
When a set to min in bar chart settings always start in zero.
If I change to max and comeback to min work ok, but at midnight, whem reset values the same problem.
Wait a fix.
Thanks a lot

**Comment by arneman** [comment]
You were right. Thank you for the good descriptions. I've fixed it and will publish an new version this evening.

Regards

Arne
