### ISSUE TITLE
Can you give more details (examples) how to do the "persistent node" configuration

### ISSUE THREAD

**Issue by Soiski71** [arneman/node-red-contrib-dashboard-bar-chart-data#8]
Can you give more details (examples) how to do the "persistent node" configuration. Your help file comment does not open it to me atleast:

Restore
If you put the output of this node to the input of this kind of node (via persist node), the data will be restored. This could be helpful to avoid getting a blank bar-chart after node-red has been restarted (reboot).

This for the reason that some of my charts seems to lose some data periodically and this might help me to fix the issue.

**Comment by arneman** [comment]
Maybe this can help you: https://flows.nodered.org/node/node-red-contrib-persist

The persist node stores messages to a file system and restores them after node-red will be restarted.

Another way to archive a restore is to enable context data to file system in the node-red settings.js, see https://nodered.org/docs/user-guide/context

maybe this flow (import into node red) helps you to understand it. With the output of the first node you can "restore" the second node.

`[
    {
        "id": "5640b260bdc90f7c",
        "type": "inject",
        "z": "4cf5c50725c23269",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "testmin",
        "payload": "10",
        "payloadType": "num",
        "x": 140,
        "y": 120,
        "wires": [
            [
                "dc10a907ff7f051d"
            ]
        ]
    },
    {
        "id": "f9651a85bc918768",
        "type": "inject",
        "z": "4cf5c50725c23269",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "testmin",
        "payload": "5",
        "payloadType": "num",
        "x": 140,
        "y": 160,
        "wires": [
            [
                "dc10a907ff7f051d"
            ]
        ]
    },
    {
        "id": "6fc0ce9ac81790a3",
        "type": "inject",
        "z": "4cf5c50725c23269",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "testmin",
        "payload": "4",
        "payloadType": "num",
        "x": 140,
        "y": 200,
        "wires": [
            [
                "dc10a907ff7f051d"
            ]
        ]
    },
    {
        "id": "dc10a907ff7f051d",
        "type": "bar-chart-data",
        "z": "4cf5c50725c23269",
        "name": "bar-chart-data",
        "x_interval": "minutes",
        "x_size": 24,
        "unit": "",
        "precision": 2,
        "is_meter_reading": "False",
        "agg_by": "min",
        "x": 460,
        "y": 160,
        "wires": [
            [
                "7c74b28c89b456b4",
                "c611eff597d270c1"
            ]
        ]
    },
    {
        "id": "5e7862394c18720e",
        "type": "inject",
        "z": "4cf5c50725c23269",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "testmin",
        "payload": "clear",
        "payloadType": "str",
        "x": 150,
        "y": 240,
        "wires": [
            [
                "dc10a907ff7f051d"
            ]
        ]
    },
    {
        "id": "7c74b28c89b456b4",
        "type": "ui_chart",
        "z": "4cf5c50725c23269",
        "name": "",
        "group": "c716d8f1.4bb848",
        "order": 1,
        "width": 0,
        "height": 0,
        "label": "chart",
        "chartType": "bar",
        "legend": "false",
        "xformat": "HH:mm:ss",
        "interpolate": "linear",
        "nodata": "",
        "dot": false,
        "ymin": "",
        "ymax": "",
        "removeOlder": 1,
        "removeOlderPoints": "",
        "removeOlderUnit": "3600",
        "cutout": 0,
        "useOneColor": false,
        "useUTC": false,
        "colors": [
            "#1f77b4",
            "#aec7e8",
            "#ff7f0e",
            "#2ca02c",
            "#98df8a",
            "#d62728",
            "#ff9896",
            "#9467bd",
            "#c5b0d5"
        ],
        "outputs": 1,
        "useDifferentColor": false,
        "className": "",
        "x": 830,
        "y": 160,
        "wires": [
            []
        ]
    },
    {
        "id": "c611eff597d270c1",
        "type": "bar-chart-data",
        "z": "4cf5c50725c23269",
        "name": "bar-chart-data",
        "x_interval": "minutes",
        "x_size": 24,
        "unit": "",
        "precision": 2,
        "is_meter_reading": "False",
        "agg_by": "min",
        "x": 680,
        "y": 240,
        "wires": [
            [
                "a0b399b6f7823c83"
            ]
        ]
    },
    {
        "id": "a0b399b6f7823c83",
        "type": "ui_chart",
        "z": "4cf5c50725c23269",
        "name": "",
        "group": "c716d8f1.4bb848",
        "order": 1,
        "width": 0,
        "height": 0,
        "label": "chart",
        "chartType": "bar",
        "legend": "false",
        "xformat": "HH:mm:ss",
        "interpolate": "linear",
        "nodata": "",
        "dot": false,
        "ymin": "",
        "ymax": "",
        "removeOlder": 1,
        "removeOlderPoints": "",
        "removeOlderUnit": "3600",
        "cutout": 0,
        "useOneColor": false,
        "useUTC": false,
        "colors": [
            "#1f77b4",
            "#aec7e8",
            "#ff7f0e",
            "#2ca02c",
            "#98df8a",
            "#d62728",
            "#ff9896",
            "#9467bd",
            "#c5b0d5"
        ],
        "outputs": 1,
        "useDifferentColor": false,
        "className": "",
        "x": 870,
        "y": 240,
        "wires": [
            []
        ]
    },
    {
        "id": "c716d8f1.4bb848",
        "type": "ui_group",
        "name": "bar-chart",
        "tab": "957fd14a.a1277",
        "order": 1,
        "disp": true,
        "width": "12",
        "collapse": false
    },
    {
        "id": "957fd14a.a1277",
        "type": "ui_tab",
        "name": "bar-chart",
        "icon": "dashboard",
        "disabled": false,
        "hidden": false
    }
]`
